# Generated by Django 3.0.7 on 2020-09-30 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Order', '0002_auto_20200930_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choice', models.CharField(choices=[('PIZZA', 'PZ'), ('MACCARONI', 'MCC'), ('PASTA', 'PST'), ('Burger', 'BG'), ('Chicken', 'CHK')], default='PIZZA', max_length=100)),
                ('F', models.IntegerField(default=0)),
                ('B', models.IntegerField(default=0)),
                ('buyer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Order.Employee')),
            ],
        ),
    ]
